//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAppAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ChatCollegeDataBaseEntities : DbContext
    {
        public ChatCollegeDataBaseEntities()
            : base("name=ChatCollegeDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessageTable> ChatMessageTable { get; set; }
        public virtual DbSet<ChatRoomTable> ChatRoomTable { get; set; }
        public virtual DbSet<ChatRoomUserTable> ChatRoomUserTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UsersTable> UsersTable { get; set; }
    }
}
