//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAppAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatRoomTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatRoomTable()
        {
            this.ChatMessageTable = new HashSet<ChatMessageTable>();
            this.ChatRoomUserTable = new HashSet<ChatRoomUserTable>();
        }
    
        public int PersonalNumberChatRoom { get; set; }
        public string TopicChatRoom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<ChatMessageTable> ChatMessageTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<ChatRoomUserTable> ChatRoomUserTable { get; set; }
    }
}
